name: Release-Tag
on:
  push:
    branches: [ master, main ] 
    paths-ignore:
      - '**.md' ### Ignore running when .md files change
      - '**.yaml' ### Ignore running when .yaml files change
      - '**.json' ### Ignore running when .json files change
      - '.github/*' ### Ignore running when files under path: .github/* changed.


jobs:
  test:
    permissions:
      pull-requests: write
    uses: kubescape/workflows/.github/workflows/package-release.yaml@main
    with:
      GO_VERSION: 1.19
      RELEASE: "v0.0.${{ github.run_number }}"
    secrets: inherit
 